### ISSUE TITLE
Flag scope "splatter" is not valid or not currently active

### ISSUE THREAD

**Issue by Talutha** [shemetz/tokenmagic-automatic-wounds#18]
Hello,

I'm not sure when this started occurring but I recently noticed the splatter not working on the tokens. I get this error in the console every time I adjust someone's HP or use one of the macros included with the module. I currently use this with Pathfinder 2e. I have not tried it with all my other modules deactivated. I posted this pretty close to my session starting so I can do some more troubleshooting later if you need. Let me know if you need anything else, thanks!

```js
Uncaught (in promise) Error: undefined. Flag scope "splatter" is not valid or not currently active
[Detected 2 packages: tokenmagic-automatic-wounds, system:pf2e]
    at _TokenDocumentPF2e2.getFlag (commons.js:8174:44)
    at getSplatterBloodColor (module-compatibility.js:24:36)
    at createWoundOnToken (tokenmagic-automatic-wounds.js:49:8)
    at Object.onPreUpdateActor [as fn] (tokenmagic-automatic-wounds.js:40:26)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at #preUpdateDocumentArray (foundry.js:13589:44)
    at async ClientDatabaseBackend._updateDocuments (foundry.js:13364:22)
    at async CharacterPF2e.updateDocuments (commons.js:7907:23)
    at async _ActorPF2e2.update (commons.js:8004:23)
    at async _ActorPF2e2.applyDamage (pf2e.mjs:36:227191)
```

**Comment by shemetz** [comment]
For now you can work around this bug by turning the splatter module on (you have it turned off).  I'll also fix it and release a version with a fix today!
